### ISSUE TITLE
Could this repo reproduce paper results?

### ISSUE THREAD

**Issue by riven314** [advaitrane/GANimorph_pytorch#1]
thanks for the great work! 
just wonder if your implementation could reproduce (part of) paper results? 
and what is your ```feature_match_loss()``` in the notebook?

**Comment by advaitrane** [comment]
Hi! Apologies for taking so long.
We did have trouble reproducing the paper results. I suppose there are a lot of improvements that could be made to this code. 
I have added the function definition of feature_match_loss() in the latest commit. Hope it helps!

**Comment by riven314** [comment]
thanks for the address!
